name: Test action

on:
  workflow_call:
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-test-action
  cancel-in-progress: true


jobs:
  config:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    outputs:
      configs: ${{ steps.result.outputs.configs }}
    steps:
      - id: result
        env:
          JSON: '{ os: ["ubuntu-latest", "windows-latest", "macos-latest"] }'
        run: echo "configs=$JSON" >> "$GITHUB_OUTPUT"


  check-the-same-repository:
    needs: config
    strategy:
      matrix: ${{ fromJson(needs.config.outputs.configs) }}
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - uses: ./
        with:
          tag: newTagName

      - run: echo 'Successfully checked!'

      - continue-on-error: true
        uses: ./
        with:
          tag: 0.0.0

      - if: ${{ failure() }}
        run: exit 1

      - run: echo 'Duplicates successfully detected!'


  check-the-other-repository:
    needs: config
    strategy:
      matrix: ${{ fromJson(needs.config.outputs.configs) }}
      max-parallel: 1
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/create-github-app-token
      - name: Create token for dist repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: tshion
          repositories: apply-git-user

      - uses: ./
        with:
          repository: tshion/apply-git-user
          tag: newTagName
          token: ${{ steps.app-token.outputs.token }}

      - run: echo 'Successfully checked!'

      - continue-on-error: true
        uses: ./
        with:
          repository: tshion/apply-git-user
          tag: 1.0.0
          token: ${{ steps.app-token.outputs.token }}

      - if: ${{ failure() }}
        run: exit 1

      - run: echo 'Duplicates successfully detected!'
